paths:
  kitti_depth_dataset_dir: data/kitti_depth
  kitti_rgb_dataset_dir: data/kitti_raw
training:
  num_epochs: 15
  device: cuda
  train_on: 10000
  train_batch_size: 2
  val_batch_size: 11
  save_chkpt_each: 1
  loss: SmoothL1Loss
  lr: 0.01
  lr_decay: 0.1
  lr_decay_step: 10
  optimizer: Adam
model:
  model: SNC
  rgb: False
  reflectance: False
  lidar_padding: True
  n_channels: 1
  init_method: k
  symmetric: True
  use_bias: False
  scs_pool_d: True
  occl_pool_d: False
  scs_unpool_d: True
  focused_unpool_e: False
  unfocused_unpool_e: False
  n_stages: 4